bootstrap.servers=kafka:9092
group.id=monitoring-connect
config.storage.topic=monitoring.connect.configs
offset.storage.topic=monitoring.connect.offsets
status.storage.topic=monitoring.connect.status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
offset.storage.partitions=1
status.storage.partitions=1
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
listeners=http://0.0.0.0:8083
rest.advertised.host.name=connect
plugin.path=/opt/monitoring/plugins
config.providers=file
config.providers.file.class=org.apache.kafka.common.config.provider.FileConfigProvider
